2025-08-18 01:59:56 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 02:01:03 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 02:01:05 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 02:02:26 | services.content_service | INFO | content_service.py:293 | Created new movie: Test Movie (2edc87f4-002c-4803-b0d8-b0c8e511ed4f)
2025-08-18 02:02:38 | services.content_service | INFO | content_service.py:293 | Created new movie: Test (2840e202-2fd7-4468-a222-9ea369f7b5a6)
2025-08-18 02:02:56 | services.content_service | INFO | content_service.py:293 | Created new movie: Data (3aa4d020-838c-49e5-9391-1556d5c2a8c0)
2025-08-18 02:08:51 | services.content_service | INFO | content_service.py:293 | Created new movie: Latest Test Movie (c22b3ac4-23c9-4c59-b5d1-73289a2fef2e)
2025-08-18 02:11:45 | services.content_service | INFO | content_service.py:293 | Created new movie: API Configuration Test (bef57d89-3568-4638-92cc-6968f9674d67)
2025-08-18 02:15:08 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 02:15:08 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 02:16:12 | services.content_service | INFO | content_service.py:293 | Created new movie: 1 (02f02fda-8ba4-425d-91b6-0ad6ce9c2397)
2025-08-18 02:16:17 | services.content_service | INFO | content_service.py:293 | Created new movie: vgdg (af0fbf83-3838-4f23-ab36-8ed14edad855)
2025-08-18 02:16:21 | services.content_service | INFO | content_service.py:293 | Created new movie: ssrfd (7b7911c5-9f91-41ce-8f5b-d881981b36b2)
2025-08-18 02:16:40 | services.content_service | INFO | content_service.py:293 | Created new movie: Value Check (09d0ff72-6fe6-4f4e-b62c-df0caa53d7fe)
2025-08-18 02:16:47 | services.content_service | INFO | content_service.py:293 | Created new movie: Data Input Values (cc466058-f888-426b-91f1-a666f60b342b)
2025-08-18 02:16:51 | services.content_service | INFO | content_service.py:293 | Created new movie: New Movie Name  (e840f7d4-9112-4cf9-999a-b8912264a9ed)
2025-08-18 02:17:23 | services.content_service | INFO | content_service.py:323 | Updated movie: Data Input Values 1 (cc466058-f888-426b-91f1-a666f60b342b)
2025-08-18 02:27:44 | services.content_service | INFO | content_service.py:293 | Created new movie: Data (1a4c846f-f97d-4fac-aacc-a11fe1472216)
2025-08-18 02:34:25 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 02:34:25 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 02:35:31 | services.content_service | INFO | content_service.py:356 | Started export 8c72fdc7-e0d0-496d-8e24-4c41e1b78c8d in format csv
2025-08-18 02:35:46 | services.content_service | ERROR | content_service.py:426 | Export 8c72fdc7-e0d0-496d-8e24-4c41e1b78c8d failed: 'ContentService' object has no attribute 'repository'
2025-08-18 02:36:42 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 02:36:43 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 02:36:52 | services.content_service | INFO | content_service.py:356 | Started export 800e9b1b-145f-42d2-9492-904e46ecc2fd in format csv
2025-08-18 02:36:54 | services.content_service | ERROR | content_service.py:426 | Export 800e9b1b-145f-42d2-9492-904e46ecc2fd failed: 'builtin_function_or_method' object has no attribute 'lower'
2025-08-18 02:37:32 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 02:37:33 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 02:37:40 | services.content_service | INFO | content_service.py:356 | Started export ffa9ff41-4173-45bf-aa6b-1192e9afe2f4 in format csv
2025-08-18 02:37:40 | services.content_service | INFO | content_service.py:443 | Export ffa9ff41-4173-45bf-aa6b-1192e9afe2f4 completed successfully: exports\ffa9ff41-4173-45bf-aa6b-1192e9afe2f4.csv
2025-08-18 02:39:34 | services.content_service | INFO | content_service.py:356 | Started export e106fc36-7454-4d0d-8dcf-aaa8ccf6e412 in format json
2025-08-18 02:39:34 | services.content_service | INFO | content_service.py:443 | Export e106fc36-7454-4d0d-8dcf-aaa8ccf6e412 completed successfully: exports\e106fc36-7454-4d0d-8dcf-aaa8ccf6e412.json
2025-08-18 02:47:07 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 02:47:08 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 11:03:55 | services.content_service | INFO | content_service.py:465 | Starting bulk movie import 3bbecd45-8a94-4e62-878f-adf062119095 with 5 movies, operation: upsert
2025-08-18 11:03:55 | services.content_service | INFO | content_service.py:555 | Bulk import 3bbecd45-8a94-4e62-878f-adf062119095 completed: 5 successful, 0 failed
2025-08-18 11:18:51 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 11:18:51 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 11:49:27 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 11:49:29 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 12:02:06 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import 27764d62-4a42-4305-9e43-6d301fda4c2c with 5 movies, operation: upsert
2025-08-18 12:02:06 | services.content_service | INFO | content_service.py:566 | Bulk import 27764d62-4a42-4305-9e43-6d301fda4c2c completed: 5 successful, 0 failed
2025-08-18 12:10:25 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import 7c563934-f11d-4e81-98d5-e9539609f395 with 5 movies, operation: upsert
2025-08-18 12:10:25 | services.content_service | INFO | content_service.py:566 | Bulk import 7c563934-f11d-4e81-98d5-e9539609f395 completed: 5 successful, 0 failed
2025-08-18 12:11:08 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import 4e081e07-7524-49b4-8212-3daa55bb8021 with 5 movies, operation: upsert
2025-08-18 12:11:08 | services.content_service | INFO | content_service.py:566 | Bulk import 4e081e07-7524-49b4-8212-3daa55bb8021 completed: 5 successful, 0 failed
2025-08-18 12:11:10 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import 748ce6be-b7a6-4779-8d76-794a5f7230a0 with 5 movies, operation: upsert
2025-08-18 12:11:10 | services.content_service | INFO | content_service.py:566 | Bulk import 748ce6be-b7a6-4779-8d76-794a5f7230a0 completed: 5 successful, 0 failed
2025-08-18 12:20:33 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import 83f4cdd3-fef6-46a8-8a4b-4bf1b01a950e with 10 movies, operation: upsert
2025-08-18 12:20:33 | services.content_service | ERROR | content_service.py:569 | Critical error in bulk import 83f4cdd3-fef6-46a8-8a4b-4bf1b01a950e: (pymysql.err.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO movies (id, title, genre, release_date, duration_minutes, description, director, rating, language, country, poster_url, trailer_url, status, imdb_id, tmdb_id, box_office_collection, budget, is_available, location, created_by, created_at, updated_at) VALUES (%(id)s, %(title)s, %(genre)s, %(release_date)s, %(duration_minutes)s, %(description)s, %(director)s, %(rating)s, %(language)s, %(country)s, %(poster_url)s, %(trailer_url)s, %(status)s, %(imdb_id)s, %(tmdb_id)s, %(box_office_collection)s, %(budget)s, %(is_available)s, %(location)s, %(created_by)s, %(created_at)s, %(updated_at)s)]
[parameters: {'id': '3b28961a-cb58-4ec9-a1da-1a3b7124f02b', 'title': 'Court State Vs A Nobody', 'genre': 'nan', 'release_date': datetime.datetime(2025, 1, 1, 0, 0), 'duration_minutes': None, 'description': 'nan', 'director': 'nan', 'rating': 'nan', 'language': 'Hindi', 'country': 'India', 'poster_url': 'nan', 'trailer_url': 'nan', 'status': 'Ready', 'imdb_id': 'nan', 'tmdb_id': 'nan', 'box_office_collection': nan, 'budget': nan, 'is_available': 1, 'location': '/movies/(Movies4u.Bid).Court - State vs A Nobody (2025) WEB-DL 1080p [Hin + Tam + Tel + Mal + Kan] ESub.mkv', 'created_by': None, 'created_at': datetime.datetime(2025, 8, 18, 12, 20, 33, 901508), 'updated_at': datetime.datetime(2025, 8, 18, 12, 20, 33, 901509)}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-08-18 12:20:54 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import ca337f90-b5d8-420c-965e-b21f62f827d3 with 10 movies, operation: upsert
2025-08-18 12:20:54 | services.content_service | ERROR | content_service.py:569 | Critical error in bulk import ca337f90-b5d8-420c-965e-b21f62f827d3: (pymysql.err.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO movies (id, title, genre, release_date, duration_minutes, description, director, rating, language, country, poster_url, trailer_url, status, imdb_id, tmdb_id, box_office_collection, budget, is_available, location, created_by, created_at, updated_at) VALUES (%(id)s, %(title)s, %(genre)s, %(release_date)s, %(duration_minutes)s, %(description)s, %(director)s, %(rating)s, %(language)s, %(country)s, %(poster_url)s, %(trailer_url)s, %(status)s, %(imdb_id)s, %(tmdb_id)s, %(box_office_collection)s, %(budget)s, %(is_available)s, %(location)s, %(created_by)s, %(created_at)s, %(updated_at)s)]
[parameters: {'id': 'fd76df21-1bcc-4cb1-b8bc-bbd351a8b5f5', 'title': 'Court State Vs A Nobody', 'genre': 'nan', 'release_date': datetime.datetime(2025, 1, 1, 0, 0), 'duration_minutes': None, 'description': 'nan', 'director': 'nan', 'rating': 'nan', 'language': 'Hindi', 'country': 'India', 'poster_url': 'nan', 'trailer_url': 'nan', 'status': 'Ready', 'imdb_id': 'nan', 'tmdb_id': 'nan', 'box_office_collection': nan, 'budget': nan, 'is_available': 1, 'location': '/movies/(Movies4u.Bid).Court - State vs A Nobody (2025) WEB-DL 1080p [Hin + Tam + Tel + Mal + Kan] ESub.mkv', 'created_by': None, 'created_at': datetime.datetime(2025, 8, 18, 12, 20, 54, 174391), 'updated_at': datetime.datetime(2025, 8, 18, 12, 20, 54, 174392)}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-08-18 12:26:25 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 12:26:26 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 12:40:14 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import 14a54250-35c6-462a-a959-b63a3688a5f1 with 146 movies, operation: upsert
2025-08-18 12:40:14 | services.content_service | ERROR | content_service.py:569 | Critical error in bulk import 14a54250-35c6-462a-a959-b63a3688a5f1: (pymysql.err.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO movies (id, title, genre, release_date, duration_minutes, description, director, rating, language, country, poster_url, trailer_url, status, imdb_id, tmdb_id, box_office_collection, budget, is_available, location, created_by, created_at, updated_at) VALUES (%(id)s, %(title)s, %(genre)s, %(release_date)s, %(duration_minutes)s, %(description)s, %(director)s, %(rating)s, %(language)s, %(country)s, %(poster_url)s, %(trailer_url)s, %(status)s, %(imdb_id)s, %(tmdb_id)s, %(box_office_collection)s, %(budget)s, %(is_available)s, %(location)s, %(created_by)s, %(created_at)s, %(updated_at)s)]
[parameters: {'id': '40c14f39-9ed4-4ac1-8828-225c46801557', 'title': 'Court - State vs A Nobody', 'genre': 'Drama, Legal', 'release_date': nan, 'duration_minutes': None, 'description': 'nan', 'director': 'nan', 'rating': 'nan', 'language': 'Hindi', 'country': 'India', 'poster_url': 'nan', 'trailer_url': 'nan', 'status': 'Ready', 'imdb_id': 'nan', 'tmdb_id': 'nan', 'box_office_collection': nan, 'budget': nan, 'is_available': 1, 'location': '/movies/court___state_vs_a_nobody.mkv', 'created_by': None, 'created_at': datetime.datetime(2025, 8, 18, 12, 40, 14, 661269), 'updated_at': datetime.datetime(2025, 8, 18, 12, 40, 14, 661277)}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-08-18 12:43:16 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import 6426e580-b053-4203-8683-25c9feb13278 with 146 movies, operation: upsert
2025-08-18 12:43:16 | services.content_service | ERROR | content_service.py:569 | Critical error in bulk import 6426e580-b053-4203-8683-25c9feb13278: (pymysql.err.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO movies (id, title, genre, release_date, duration_minutes, description, director, rating, language, country, poster_url, trailer_url, status, imdb_id, tmdb_id, box_office_collection, budget, is_available, location, created_by, created_at, updated_at) VALUES (%(id)s, %(title)s, %(genre)s, %(release_date)s, %(duration_minutes)s, %(description)s, %(director)s, %(rating)s, %(language)s, %(country)s, %(poster_url)s, %(trailer_url)s, %(status)s, %(imdb_id)s, %(tmdb_id)s, %(box_office_collection)s, %(budget)s, %(is_available)s, %(location)s, %(created_by)s, %(created_at)s, %(updated_at)s)]
[parameters: {'id': '28f43503-b32e-437a-9098-49efa80a127d', 'title': 'Court - State vs A Nobody', 'genre': 'Drama, Legal', 'release_date': nan, 'duration_minutes': None, 'description': 'nan', 'director': 'nan', 'rating': 'nan', 'language': 'Hindi', 'country': 'India', 'poster_url': 'nan', 'trailer_url': 'nan', 'status': 'Ready', 'imdb_id': 'nan', 'tmdb_id': 'nan', 'box_office_collection': nan, 'budget': nan, 'is_available': 1, 'location': '/movies/court___state_vs_a_nobody.mkv', 'created_by': None, 'created_at': datetime.datetime(2025, 8, 18, 12, 43, 16, 52016), 'updated_at': datetime.datetime(2025, 8, 18, 12, 43, 16, 52018)}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-08-18 12:43:59 | services.content_service | INFO | logger.py:78 | Logger initialized for services.content_service
2025-08-18 12:43:59 | services.content_service | INFO | content_service.py:33 | Initializing Content Service with database connection
2025-08-18 12:44:08 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import a1069824-b285-48a0-a3e9-08c8e0fa371e with 5 movies, operation: upsert
2025-08-18 12:44:08 | services.content_service | INFO | content_service.py:566 | Bulk import a1069824-b285-48a0-a3e9-08c8e0fa371e completed: 5 successful, 0 failed
2025-08-18 12:45:32 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import 49a561fa-da34-4fbe-8e68-9b7117265a13 with 146 movies, operation: upsert
2025-08-18 12:45:32 | services.content_service | INFO | content_service.py:566 | Bulk import 49a561fa-da34-4fbe-8e68-9b7117265a13 completed: 146 successful, 0 failed
2025-08-18 12:46:39 | services.content_service | INFO | content_service.py:476 | Starting bulk movie import f5171970-4fe9-4ab8-8258-584db8d9e87b with 146 movies, operation: upsert
2025-08-18 12:46:40 | services.content_service | INFO | content_service.py:566 | Bulk import f5171970-4fe9-4ab8-8258-584db8d9e87b completed: 146 successful, 0 failed
